#ifndef ENERGI_CHAINPARAMSSEEDS_H
#define ENERGI_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the energi network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x00,0x00,0x00,0x00}, 9797} // no main net seeds yet
};

static SeedSpec6 pnSeed6_test[] = {

    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x36,0xCA,0x59,0x6E}, 19797}
};
#endif // ENERGI_CHAINPARAMSSEEDS_H
